// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaUTptS_ELldTKBbPTlNy3VqCf1gfjp5k',
    appId: '1:469208507961:web:c5a7b04bd0891e67bb0fe8',
    messagingSenderId: '469208507961',
    projectId: 'myschooling-98ac7',
    authDomain: 'myschooling-98ac7.firebaseapp.com',
    storageBucket: 'myschooling-98ac7.appspot.com',
    measurementId: 'G-EW9JEZJ1HL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPq2QuglBulzb0qV3C4IFpvSzCByDnhg8',
    appId: '1:469208507961:android:39c958e2a6335e4bbb0fe8',
    messagingSenderId: '469208507961',
    projectId: 'myschooling-98ac7',
    storageBucket: 'myschooling-98ac7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh5uG6zN6p5gkkGiHAkyyhiVpWFsH-6vY',
    appId: '1:469208507961:ios:cb59c7ef3c8848afbb0fe8',
    messagingSenderId: '469208507961',
    projectId: 'myschooling-98ac7',
    storageBucket: 'myschooling-98ac7.appspot.com',
    iosBundleId: 'com.example.finalschool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh5uG6zN6p5gkkGiHAkyyhiVpWFsH-6vY',
    appId: '1:469208507961:ios:4353d687167d540bbb0fe8',
    messagingSenderId: '469208507961',
    projectId: 'myschooling-98ac7',
    storageBucket: 'myschooling-98ac7.appspot.com',
    iosBundleId: 'com.example.finalschool.RunnerTests',
  );
}
